apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: devops-app
type: Opaque
stringData:
  postgres-db: appdb
  postgres-user: app
  postgres-password: app_password
  database-url: postgresql://app:app_password@postgres:5432/appdb
